#+TITLE: Exploratory Text Analysis and Visualization of Text Data for Research with Open-source Tools
#+AUTHOR: Scott Bailey

* Presenter

[[https://www.lib.ncsu.edu/staff/csbaile3)][Scott Bailey]]
Digital Research and Scholarship Librarian
Copyright and Digital Scholarship Center
[[https://www.lib.ncsu.edu][NC State University Libraries]]

* Exploratory text analysis

What is exploratory text analysis? Sometimes researchers working on a project approach their text corpora with clear research questions, predetermined methods, and a clear sense of the quality and nature of the corpora. You may know you are going to use some sort of classification method, and the corpus is well-described with metadata and already cleaned. Much of the time, though, we're working with text corpora that haven't been cleaned, and aren't well described. We might have large collections of text from the internet, or be working with a collections of digitized novels that come from multiple sources with varying quality of metadata. You might have a set of a couple of hundred interviews that have been automatically transcribed, and not checked for accuracy. In these cases, even if you know your research questions and have a sense of method or approach, you'll rarely be able to simply start on your analysis, whether you're writing code or not. You first need to take time to explore the text data you have, to get a sense of the quality of the data and their contents. You need to develop a sense of the shape of your data across documents, and understand potential features that might be relevant to your preliminary questions.

This is exploratory text analysis, this stage where we get to know our texts. Our goal today is to explore two open source tools that don't require the capacity to write code, but that still provide tremendous value in the research process. Depending on your research questions and methods, either tool may actually be sufficient for your research, but either or both could operate as first step in a research process that involves other tools, whether in code or not.


* Voyant
** Installing Voyant vs using the hosted web version
Download and install page: https://digihum.mcgill.ca/voyant/resources/run-your-own/voyant-server/

Advantage in speed and corpus size since you can modify the memory available to Voyant.
** File types and corpus building
Voyant can handle single documents, either by uploading them or simply copying text into the Voyant home screen input box. It provides even more power, though, when you upload many documents as a corpus.

Supported file types:
- plain text: .txt
- HTML: .htm, .html
- XML: .xml
- Word: .doc, .docx
- RTF: .rtf
- PDF: .pdf

** Exploring the interface
- Basic layout
- Getting help for each tool
- Settings for each tool
- Clicking on a document or word in one tool typically causes the other tools to update accordingly
** Tools of note
- Summary
- Contexts
- Correlations
- Trends
- Topics (Hidden by default)
** Exporting results
- Exporting visualizations
- Exporting data

* Taguette
** Installing Taguette vs using the hosted web version
Download and install page: https://www.taguette.org/install.html
** File types

** Coding documents
- Single level and hierarchical coding
** Exporting results
- Exporting collated tagged texts

* Putting it together: between distant and close reading
Research, especially with data, is iterative. We learn something from or about our data through visualization or applying some method or tool. With what we learn, we come back to our data with new interpretive possibilities and with new ideas.

Working with Voyant and Taguette together allows us to move between distant reading and close reading. In Voyant we see patterns of language across an entire corpus. We can then move into individual texts with an eye toward the patterns and themes we observed through Voyant. As we discover in individual texts new and surprising language, we can return to the corpus-level analytics of Voyant looking for correlations of those words or patterns of use over time.

* Resources:
- Voyant Docs: https://digihum.mcgill.ca/voyant/
- Voyant Tools Docs: http://docs.voyant-tools.org/tools/
- UC Santa Cruz Getting Started with Voyant: https://guides.library.ucsc.edu/DSCguides/Voyant
- Taguette Getting Started Guide: https://www.taguette.org/getting-started.html
- Illinois Library Coding with Taguette Guide: https://guides.library.illinois.edu/qualitative/taguette
