#+TITLE: Exploratory Text Analysis and Visualization of Text Data for Research with Open Source Tools
#+AUTHOR: Scott Bailey

* Presenter

[[https://www.lib.ncsu.edu/staff/csbaile3][Scott Bailey]] \\
Digital Research and Scholarship Librarian \\
Copyright and Digital Scholarship Center \\
[[https://www.lib.ncsu.edu][NC State University Libraries]]

* Exploratory text analysis and visualization in the research context

Key take-aways:
1. Text corpora exist with a wide range of metadata, cleanliness, and quality.
2. Even when we have a good sense of method or approach, exploring our data, whether quantitative or qualitative, helps us refine research questions, fine-tune methods, and scope our project to be successful.
3. Voyant and Taguette are free and open source tools that allow you analyze and visualize texts, whether as single documents or whole corpora.

* Voyant - Demo
** Installing Voyant vs using the hosted web version
Download and install page: https://digihum.mcgill.ca/voyant/resources/run-your-own/voyant-server/

Advantage in speed and corpus size since you can modify the memory available to Voyant.
** File types and corpus building
Voyant can handle single documents, either by uploading them or simply copying text into the Voyant home screen input box. It provides even more power, though, when you upload many documents as a corpus.

Supported file types:
- plain text: .txt
- HTML: .htm, .html
- XML: .xml
- Word: .doc, .docx
- RTF: .rtf
- PDF: .pdf

** Exploring the interface
- Basic layout
- Getting help for each tool
- Settings for each tool
- Clicking on a document or word in one tool typically causes the other tools to update accordingly
** Tools of note
- Summary
- Contexts
- Correlations
- Trends
- Topics (Hidden by default)
** Exporting results
- Exporting visualizations
- Exporting data

* Taguette - Demo
** Installing Taguette vs using the hosted web version
Download and install page: https://www.taguette.org/install.html
** File types
Supported file types:
- plain text: .txt
- HTML: .htm, .html
- Word: .doc, .docx
- RTF: .rtf
- PDF: .pdf
- Open Documents: .odt
- E-books: .epub, .mobi

** Coding documents
- Single level and hierarchical coding
** Exporting results
- Exporting collated tagged texts

* Putting it together: between distant and close reading

Key take-aways:
1. Distant reading allows us to analyze and draw conclusions from collections of texts at large scale.
2. Close reading helps us develop a nuanced understanding of texts.
3. Research is iterative, and moving between distant and close reading allows us to develop interpretations and conclusions that draw on the whole of a corpus without losing the nuance.

* Resources:
- Voyant Docs: https://digihum.mcgill.ca/voyant/
- Voyant Tools Docs: http://docs.voyant-tools.org/tools/
- UC Santa Cruz Getting Started with Voyant: https://guides.library.ucsc.edu/DSCguides/Voyant
- Taguette Getting Started Guide: https://www.taguette.org/getting-started.html
- Illinois Library Coding with Taguette Guide: https://guides.library.illinois.edu/qualitative/taguette
